### ISSUE TITLE
New urls for validCaptchaUrl regex

### ISSUE THREAD

**Issue by doguhanokumus** [arc298/tiktok-captcha-solver#12]
https://github.com/arc298/tiktok-captcha-solver/blob/c4d1d06b39d429f69e0d028362509e6a87412f9f/src/CaptchaSolver.js#L278

I think things changed since last commit and I ended up using the following regex:
`/(captcha|security)-\S{2,2}\.ibyteimg\.com\/(\S+)(-2\.jpeg|_1\.jpg\~tp)/gi`

**Comment by arc298** [comment]
@doguhanokumus Updated, thank you!
