### ISSUE TITLE
Non headless produces ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by malec** [arc298/tiktok-captcha-solver#9]
"Seems as if TikTok detecting chromium being controlled by playwright/puppeteer and messing up the response with `ERR_INVALID_RESPONSE`. The tests are more consistent when run in `headless: false`..."

_Originally posted by @arc298 in https://github.com/arc298/tiktok-captcha-solver/pull/7#issuecomment-956947240_

**Comment by malec** [comment]
Puppeteer has a stealth plug-in that should fix this.

**Comment by arc298** [comment]
https://www.npmjs.com/package/puppeteer-extra-plugin-stealth does seem to work however a plugin does not exist yet for playwright. None of the workarounds I tried worked, so for now have commented out the test for playwright - chromium.
